import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  background: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: "100%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    padding: 10,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 50,
    backgroundColor: "#FFF6FB",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 16,
    color: "#474146",
  },
  dateAndStreak: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  dateText: {
    fontSize: 16,
    color: "#474146",
    marginHorizontal: 5,
  },
  headerBubble: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 50,
    padding: 10,
    marginHorizontal: 5,
  },
  body: {
    flex: 1,
    marginBottom: 100,
    padding: 10,
  },
  bodyBubble: {
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 33,
    paddingHorizontal: 15,
    paddingVertical: 30,
    marginVertical: 5,
  },
  greetingText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 24,
    color: "#474146",
  },
  questionText: {
    fontFamily: "PlayfairDisplay-Regular",
    fontSize: 36,
    color: "#474146",
    letterSpacing: -1,
    textAlign: "center",
    marginBottom: 20,
  },
  actionButton: {
    margin: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  inputSection: {
    backgroundColor: "white",
    borderRadius: 33,
    marginTop: 20,
    padding: 20,
  },
  inputLabel: {
    fontFamily: "Quicksand-Regular",
    fontSize: 20,
    color: "#474146",
    marginBottom: 15,
  },
  textInput: {
    fontFamily: "Quicksand-Regular",
    borderWidth: 1,
    borderColor: "#474146",
    borderRadius: 33,
    padding: 20,
    fontSize: 16,
    opacity: 0.75,
    color: "#474146",
    backgroundColor: "#F6FFFE",
    textAlignVertical: "top",
    minHeight: 150,
  },
  calendar: {
    backgroundColor: "transparent",
    color: "transparent",
    height: 350,
    width: 320,
  },
  calendarTheme: {
    backgroundColor: "transparent",
    calendarBackground: "transparent",
    selectedDayBackgroundColor: "#00adf5",
    todayTextColor: "#00adf5",
    arrowColor: "#474146",
    monthTextColor: "#474146",
    textDayFontFamily: "Quicksand-Regular",
    textMonthFontFamily: "Quicksand-Regular",
    textDayHeaderFontFamily: "Quicksand-Regular",
    textDayFontSize: 16,
    textMonthFontSize: 24,
    textDayHeaderFontSize: 16,
  },
  titleText: {
    fontFamily: "Quicksand-Bold",
    fontSize: 24,
    color: "#474146",
  },
  detailText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 16,
    color: "#474146",
    margin: 5,
    textAlign: "left",
  },
  smallDetailText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 14,
    color: "#474146",
    marginLeft: 15,
    textAlign: "left",
  },
  barChart: {
    alignSelf: "center",
    padding: 10,
    marginBottom: 20,
  },
  goBackIcon: {
    backgroundColor: "#C1EBF2",
    borderRadius: 50,
    padding: 10,
    alignSelf: "flex-start",
  },
});
